onlydustxyz/marketplace-api

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/GithubRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/WebSecurityAdapter.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/GithubInstallationMapper.java, bootstrap/pom.xml, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/RestApiConfiguration.java, bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/GithubApiIT.java, bootstrap/src/test/resources/staging_db/scripts/6-add_indexer_exp_sample.sql, domain/src/main/java/onlydust/com/marketplace/api/domain/model/GithubAccount.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/GithubRepo.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/GithubInstallationFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/GithubStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/GithubInstallationService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/RetriedGithubInstallationFacade.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/GithubInstallationServiceTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresGithubAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/GithubAccountEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/GithubRepoEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/GithubAccountMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/GithubRepoMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/GithubAccountRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- get github account service
- get github installation REST API
- implement github account repository
- map rest adapter to domain logic
- handle not found
- retry calls pending event reception
=> Publish github installation fetch REST API

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/MeApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/UserFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/UserStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/UserService.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/UserServiceTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresUserAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/old/ApplicationRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
Devra etre rebasée une fois que la PR accept-invitations est mergée.
=> Implement new endpoint to allow users to apply on projects

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/UsersRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/UserMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/UserProfileApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/UserProfileUpdateApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/UsersApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/Contact.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/UserAllocatedTimeToContribute.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/UserProfile.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/UserProfileCover.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/UserFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/UserStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/UserService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/UserProfileView.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/UserServiceTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresUserAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/UserProfileEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/UserProfileInfoEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/type/ContactInformationIdEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/UserMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomUserRepository.java, infrastructure/postgres-adapter/src/test/java/onlydust/com/marketplace/api/postgres/adapter/it/repository/AllRepositoriesIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
Note for the frontend:
- private profile (the one of the logged user) must be get via /me/profile
- public profile of any user can be get via /users/{id}
=> Refactor GET profile and add PUT profile

.github/workflows/backend-ci.yml, bootstrap/src/test/resources/staging_db/dump/.gitattributes, bootstrap/src/test/resources/staging_db/dump/od_staging_dump.sql, bootstrap/src/test/resources/staging_db/dump/od_staging_indexer_exp_dump.sql
- remove staging dumps
- upload staging dumps to LFS
=> Upload staging dumps to LFS

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/ContributionMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/GetContributionsDetailsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/MeGetContributionsApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/CodeReviewState.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ContributionBaseView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ContributionDetailsView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ContributionLinkView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ContributionView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/PullRequestReviewState.java, domain/src/test/java/onlydust/com/marketplace/api/domain/view/ContributionViewTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/CodeReviewState.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ContributionDetailsViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ContributionViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ContributionDetailsViewEntityRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ContributionViewEntityRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- create pull request review state logic
- return pull request review state in REST API
- update queries
- create integration test
=> [B-1134] Return aggregated code review outcome in case of a pr

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/ProjectCreateUpdateIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/ProjectRefreshIgnoredContributionsIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/IndexerPort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/ProjectStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/ProjectService.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/ProjectServiceTest.java, infrastructure/indexer-api-client-adapter/src/main/java/onlydust/com/marketplace/api/indexer/api/client/adapter/IndexerApiClientAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/old/ProjectRepoRepository.java
- implement domain logic
- implement adapters
- fix integration tests
- make create update project transactional
=> [B-1167] Remove a repo from full indexing when no longer linked to any project

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/MyRewardMapper.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/ProjectRewardMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardsApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/UserFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/UserStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/UserService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/Money.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/UserRewardView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/UserRewardsPageView.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresUserAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/RewardStatsEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomUserRewardRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardStatsRepository.java, infrastructure/postgres-adapter/src/test/java/onlydust/com/marketplace/api/postgres/adapter/it/repository/CustomUserRewardRepositoryIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- add rewards stats in get user rewards response
- handle multiple currencies in return
- add filters
- deduplicate results
=> [B-1226] Add rewards stats to GET my rewards endpoint

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ContributorSearchIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetContributedProjectsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetContributedReposApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetContributionsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsGetRewardableItemsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsPostRewardableOtherIssueApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsPostRewardableOtherPullRequestApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsPostRewardableOtherWorkApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/GithubRepoViewEntityRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ShortProjectViewEntityRepository.java
- sort contributed projects by name
- sort contributed repos by name
=> Sort contributed projects and repos by name

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, bootstrap/src/test/resources/application-it.yaml, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/BackofficeFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/BackofficeStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/BackofficeService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/backoffice/UserView.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresBackofficeAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/backoffice/read/BoUserEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/backoffice/BoUserRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/backoffice/ProjectLeadInvitationRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000016_add_tech_columns_in_user_profiles.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- return languages as array
- add user updated at
- add project filtering
=> Fix some issues in backoffice endpoints

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, bootstrap/src/test/resources/application-it.yaml, domain/src/main/java/onlydust/com/marketplace/api/domain/model/UserPayoutInformation.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/backoffice/PaymentView.java, domain/src/test/java/onlydust/com/marketplace/api/domain/view/backoffice/PaymentViewTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/backoffice/read/BoPaymentEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/type/UsdPreferredMethodEnumEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/backoffice/BoPaymentRepository.java
- add payout info missing in payment list
- remove trace logging
=> Compute payout info missing for back-office

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/ProjectsRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/ContributorMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectGetInsightsApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/ProjectFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/ProjectStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/ProjectService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/NewcomerView.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ChurnedContributorViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/NewcomerViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/type/ProfileCoverEnumEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/NewcomerViewEntityRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- implement insights newcomers endpoint
- bug fix
=> [B-1244] Implement newcomers endpoint

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/ProjectsRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/ContributorMapper.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/UserMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectGetInsightsApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/ProjectFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/ProjectStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/ProjectService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ContributorActivityView.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ContributorActivityViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/UserProfileEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ContributorActivityViewEntityRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomUserRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- implement insights newcomers endpoint
- bug fix
- implement insight most active contributors endpoint
=> [B-1245] Implement most actives contributors endpoint

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectGetInsightsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/backoffice/read/BoPaymentEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/backoffice/read/BoUserEntity.java
- fix wrong sql type
- fix flaky test
=> Fix SQL queries and CI

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/ContributorMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectGetInsightsApiIT.java
- fix wrong sql type
- fix flaky test
- add empty counters for missing weeks in contriution stats
=> Add empty stats when no contribution

.github/workflows/backend-ci.yml, application/cron-adapter/pom.xml, bootstrap/pom.xml, coverage/pom.xml, domain/pom.xml, infrastructure/aws-s3-adapter/pom.xml, infrastructure/postgres-adapter/pom.xml, pom.xml
- setup jacoco + add missing modules
- upload code coverage report to codecov.io
=> Compute and upload code coverage

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/auth0/Auth0JwtClaims.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/auth0/Auth0JwtService.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/hasura/HasuraJwtService.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/UserMapper.java, application/rest-api-adapter/src/test/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/AuthenticationServiceTest.java, application/rest-api-adapter/src/test/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/auth0/Auth0JwtServiceTest.java, application/rest-api-adapter/src/test/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/hasura/HasuraJwtServiceTest.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/helper/JwtVerifierStub.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/Auth0MeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/HasuraAuthMeApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/GithubUserIdentity.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/User.java, domain/src/main/java/onlydust/com/marketplace/api/domain/observer/UserObserver.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/UserFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/UserStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/GithubAccountService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/TechnologiesService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/UserService.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/GithubAccountServiceTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/TechnologiesServiceTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/UserServiceTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresUserAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/UserViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/UserEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/UserMapper.java, infrastructure/postgres-adapter/src/test/java/onlydust/com/marketplace/api/postgres/adapter/it/repository/AllRepositoriesIT.java, infrastructure/postgres-adapter/src/test/java/onlydust/com/marketplace/api/postgres/adapter/it/repository/CustomUserPayoutInfoRepositoryIT.java, infrastructure/postgres-adapter/src/test/java/onlydust/com/marketplace/api/postgres/adapter/it/repository/PostgresUserAdapterIT.java
Draft pour qu'on MEP avant de merger celle-la.
=> Get email from Auth0 JWT and save it into iam.users

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/OdRustApiClientConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardingProjectsApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/ContributorFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/RewardServicePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/RewardStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/ContributorService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/RewardService.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/ContributorServiceTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/RewardServiceTest.java, infrastructure/od-rust-api-client-adapter/src/main/java/onlydust/com/marketplace/api/od/rust/api/client/adapter/OdRustApiClientAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresRewardAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ShortProjectViewEntityRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- reword reward storage to reward service
- create my rewarding projects endpoint
=> [B-1294] Create /me/rewarding-projects endpoint

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/RewardMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/Aptos.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/BlockExplorer.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/Blockchain.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/Ethereum.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/Hash.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/Optimism.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/StarkNet.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/aptos/AccountAddress.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/aptos/AptoScan.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/aptos/TransactionHash.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/evm/AccountAddress.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/evm/TransactionHash.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/evm/ethereum/EtherScan.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/evm/ethereum/Name.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/evm/ethereum/Wallet.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/evm/optimism/EtherScan.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/starknet/AccountAddress.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/starknet/StarkScan.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/blockchain/starknet/TransactionHash.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ReceiptView.java, domain/src/test/java/onlydust/com/marketplace/api/domain/model/blockchain/AptosTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/model/blockchain/EthereumTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/model/blockchain/OptimismTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/model/blockchain/StarkNetTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/type/CryptoReceiptJsonEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/RewardMapper.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- proper blockchain management in domain
- create ethereum wallet in domain
- add ENS type
- add transaction reference link in receipt
=> [B-1302] Add transactionReferenceLink in API

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/UserMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectGetInsightsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/model/UserProfileCover.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ChurnedContributorView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/NewcomerView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/UserProfileView.java, domain/src/test/java/onlydust/com/marketplace/api/domain/view/ChurnedContributorViewTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/view/NewcomerViewTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/view/UserProfileViewTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomUserRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000026_shuffle_profile_covers.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- shuffle existing user covers
- random user profile cover by default
=> [E-978] Randomize cover assigned to contributor profile upon signup

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/ProjectsRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/AuthenticationService.java, application/rest-api-adapter/src/test/java/onlydust/com/marketplace/api/rest/api/adapter/authentication/AuthenticationServiceTest.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/OdRustApiClientConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/RestApiConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectDeleteRewardsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectMarkInvoiceAsReceivedRewardsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectPostRewardsApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/RewardFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/RewardServicePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/RewardService.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/RewardServiceTest.java, infrastructure/od-rust-api-client-adapter/src/main/java/onlydust/com/marketplace/api/od/rust/api/client/adapter/OdRustApiClientAdapter.java, infrastructure/od-rust-api-client-adapter/src/main/java/onlydust/com/marketplace/api/od/rust/api/client/adapter/OdRustApiHttpClient.java, infrastructure/od-rust-api-client-adapter/src/main/java/onlydust/com/marketplace/api/od/rust/api/client/adapter/dto/RequestRewardDTO.java, infrastructure/od-rust-api-client-adapter/src/main/java/onlydust/com/marketplace/api/od/rust/api/client/adapter/mapper/RewardMapper.java
See https://github.com/onlydustxyz/marketplace-backend/pull/42
=> Remove HasuraAuth jwt when calling Rust API from new API

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/ERC20Provider.java, infrastructure/infura-adapter/pom.xml, infrastructure/infura-adapter/src/main/java/onlydust/com/marketplace/api/infura/InfuraClient.java, infrastructure/infura-adapter/src/main/java/onlydust/com/marketplace/api/infura/adapters/InfuraERC20ProviderAdapter.java, infrastructure/infura-adapter/src/test/java/onlydust/com/marketplace/api/infura/adapters/InfuraERC20ProviderAdapterTest.java, infrastructure/pom.xml
- refactor http clients
- add infura package
- add web3j dependency
- create infura erc 20 provider
- handle invalid contract
=> Create Infura adapter using Web3j

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/CurrencyService.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Quote.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/CurrencyMetadataService.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/CurrencyStorage.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/QuoteService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/CurrencyServiceTest.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/stubs/Quotes.java, infrastructure/coinmarketcap-adapter/pom.xml, infrastructure/coinmarketcap-adapter/src/main/java/onlydust/com/marketplace/api/infrastructure/coinmarketcap/CmcClient.java, infrastructure/coinmarketcap-adapter/src/main/java/onlydust/com/marketplace/api/infrastructure/coinmarketcap/adapters/CmcCurrencyMetadataServiceAdapter.java, infrastructure/coinmarketcap-adapter/src/main/java/onlydust/com/marketplace/api/infrastructure/coinmarketcap/adapters/CmcQuoteServiceAdapter.java, infrastructure/coinmarketcap-adapter/src/test/java/onlydust/com/marketplace/api/infrastructure/coinmarketcap/adapters/CmcCurrencyMetadataServiceAdapterTest.java, infrastructure/coinmarketcap-adapter/src/test/java/onlydust/com/marketplace/api/infrastructure/coinmarketcap/adapters/CmcQuoteServiceAdapterTest.java, infrastructure/pom.xml, kernel/src/main/java/onlydust/com/marketplace/kernel/infrastructure/HttpClient.java
- fetch currency metadata from ERC20
- create coinmarketcap package
- create cmc http client
- cmc adapter for currency metadata
- more generic error message
- cmc quote service adapter
- refactor common logic in cmc client
- pass currency id in quote service
- fetch quotes from multiple ids
- add documentation tests
=> Implement coinmarketcap API

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/AccountBook.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/AccountBookAggregate.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/AccountBookState.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBookEvent.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountBookTest.java, kernel/src/main/java/onlydust/com/marketplace/kernel/visitor/Visitable.java, kernel/src/main/java/onlydust/com/marketplace/kernel/visitor/Visitor.java
- extract account book interface
- implement visitor pattern in kernel
- event source account book
=> Event source account book

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/CurrencyService.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/CurrencyFacadePort.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/CurrencyServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeCurrencyManagementRestApi.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/ProjectService.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/UserService.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/ProjectServiceTest.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/UserServiceTest.java, infrastructure/aws-s3-adapter/src/main/java/onlydust/com/marketplace/api/aws/s3/adapter/AwsS3Adapter.java, kernel/src/main/java/onlydust/com/marketplace/kernel/port/output/ImageStoragePort.java
- move ImageStoragePort to kernel
- allow uploading a currency logo
=> [B-1327] Allow uploading a new currency logo

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/MyRewardMapper.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/RewardMapper.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/RewardableItemMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsGetRewardApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsGetRewardableItemsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsPostRewardableOtherIssueApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsPostRewardableOtherPullRequestApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsPostRewardableOtherWorkApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/RewardItemView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/RewardableItemView.java, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/dto/IssueResponseDTO.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/RewardItemViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/RewardableItemViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/RewardMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/RewardableItemMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomRewardRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardableItemRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- add github body and author in rewardableitemsresponse
- add github body in reward item
=> Add github body and author in reward(able) items

application/cron-adapter/src/main/java/com/onlydust/marketplace/api/cron/JobScheduler.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/CronConfiguration.java, bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/input/UserFacadePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/GithubSearchPort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/port/output/UserStoragePort.java, domain/src/main/java/onlydust/com/marketplace/api/domain/service/UserService.java, domain/src/test/java/onlydust/com/marketplace/api/domain/service/UserServiceTest.java, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/adapters/GithubSearchApiAdapter.java, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/dto/GetUserEmailsResponseDTO.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresUserAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/UserRepository.java
- refresh active users profiles domain logic
- postgres adapter
- cron job
- github api adapter
- reduce test flakiness
=> [E-875] Refresh active users email, login and avatar on a regular basis

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/AccountProviderProxy.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/ContributorId.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceTest.java
- fund project from committee
- full money transfer scenario
=> Remaining funding use cases

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/ContributionMapper.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/MyRewardMapper.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/ProjectRewardMapper.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/RewardMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetContributionsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectGetContributionsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsGetRewardApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsGetRewardsApiIT.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ContributionView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/ProjectRewardView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/RewardView.java, domain/src/main/java/onlydust/com/marketplace/api/domain/view/UserRewardView.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresContributionAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ContributionViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ProjectRewardViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/UserRewardViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/ProjectRewardMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/UserRewardMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ContributionViewEntityRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomProjectRewardRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomUserRewardRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- return and sort contributions by last update time
- add processedAt in my rewards
- add processedAt in project rewards
- add unlockDate in reward details
=> [E-1038] Fix contribution sorting by date + add unlock date in rewards

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Ledger.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceTest.java
- cannot spend locked tokens
- annot spend unlock tokens if locked tokens are first
- can spend unlocked tokens
=> Handle locked tokens

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Ledger.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceTest.java
- require network to fund ledger
- require network when withdrawing funds
- cannot withdraw on incorrect network
- test with multiple networks
=> Require network for funding/withdrawing 

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Invoice.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/InvoiceFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/InvoiceStoragePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/InvoiceService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/model/InvoiceTest.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileServiceTest.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/InvoiceServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeInvoicingManagementRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/AccountingConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/BackofficeConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeInvoicingApiIT.java, bootstrap/src/test/resources/database/scripts/change_data_for_testing.sql, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresInvoiceStorage.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/CurrencyEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/InvoiceEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/InvoiceRewardEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/InvoiceRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/InvoiceRewardRepository.java
=> [B-1372] Approve/reject invoice BO endpoint

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Invoice.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/BillingProfileFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/InvoiceStoragePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeInvoicingManagementRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BillingProfileRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BillingProfileMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/InvoicesApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeInvoicingApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresInvoiceStorage.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/InvoiceRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- **fix due date computation**
- **add invoice sorting**
=> [B-1365] Add pagination and sort on the invoices list

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Invoice.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/InvoiceFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileService.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/InvoiceService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/InvoiceServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeInvoicingManagementRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/AccountingConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeInvoicingApiIT.java
- **download invoice API for BO**
- **remove old download link**
=> [B-1378] Add url for invoice download from BO

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Invoice.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/InvoiceStoragePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingObserver.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileService.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/InvoiceService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/observer/AccountingObserverTest.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileServiceTest.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/InvoiceServiceTest.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/InvoicesApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresInvoiceStorage.java
- **Fix draft clean-up when changing billing profile**
- **split invoice create and update**
=> [B-1387] Fix draft clean-up when changing billing profile

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Receipt.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/AccountingObserverPort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/ReceiptStoragePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingObserver.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceTest.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/observer/AccountingObserverTest.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/AccountingConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/PayoutPreferenceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsGetRewardsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeAccountingApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresReceiptStorage.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/RewardViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/ReceiptEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/RewardEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardViewRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000073_add_payment_receipts.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **migrate payment receipt and map queries**
- **add receipt on reward paid**
- **create postgres receipt storage**
- **handle non existing users**
- **add integration test**
- **rewards can have multiple receipts**
=> Handle payment receipts when paying rewards

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/SponsorAccountStatement.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountBookFacade.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeSponsorApiIT.java
add missing fields in get sponsor
=> add missing fields in get sponsor

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingObserver.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/DomainConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/helper/AccountingHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/ProjectsGetRewardsApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectRewardAdapter.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/ProjectRewardStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/ProjectService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/ProjectServiceTest.java
- **restore tests**
- **remove todo comments**
- **split ProjectRewardService from ProjectService**
=> split ProjectRewardService from ProjectService

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Currency.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Invoice.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Network.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/billingprofile/PayoutInfo.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/model/CurrencyTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/InvoicesApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeCurrencyApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000118_remove_swift_network.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **restore bo get users test**
- **restore invoice test**
- **remove swift network**
=> Restore some tests + remove SWIFT network

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeGetRewardsApiIT.java, bootstrap/src/test/resources/wiremock/coinmarketcap/mappings/strk-info-starknet.json, infrastructure/coinmarketcap-adapter/pom.xml, infrastructure/coinmarketcap-adapter/src/main/java/onlydust/com/marketplace/api/infrastructure/coinmarketcap/CmcClient.java, infrastructure/coinmarketcap-adapter/src/test/java/onlydust/com/marketplace/api/infrastructure/coinmarketcap/adapters/CmcQuoteServiceAdapterTest.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/HistoricalTransactionRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardViewRepository.java
- **fix count query generation**
- **fix my rewards query**
- **handle bad request from CMC**
=> [B-1414] Fix some errors on the sponsors request

accounting-domain/pom.xml, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBook.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBookAggregate.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBookState.java, application/cli-adapter/pom.xml, application/cli-adapter/src/main/java/onlydust/com/marketplace/cli/AccountBookDisplay.java, application/cli-adapter/src/main/java/onlydust/com/marketplace/cli/NewAccountingMigration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/CliConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresAccountBookEventStorage.java, pom.xml
- **export graph to dot file**
- **display subgraph of sponsor**
=> Display account book graph as dot file for investigation purposes

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/AccountingFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeAccountingManagementRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/AccountingConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/feature/RewardStatusIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeAccountingApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeBatchPaymentApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeInvoicingApiIT.java
- **remove get pending payments bo REST API**
- **fix integration test**
- **prevent paying reward that are not approved**
Closes E-1233
=> Fix CI + prevent paying reward that are not approved

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/AccountingObserverPort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/RewardStatusStorage.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingObserver.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileServiceTest.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/BillingProfileApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresRewardStatusAdapter.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000121_add_missing_foreign_key.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **create integration test to reproduce issues**
- **notify observer upon created billing profile being selected for projects**
- **create missing foreign key**
- **update rewards upon billing profile being deleted**
=> B-1449] Fix bug when creating a billing profile

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/BillingProfileFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/out/BillingProfileStoragePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileService.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/view/BillingProfileCoworkerView.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BillingProfileRestApi.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/BillingProfileCoworkersApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresBillingProfileAdapter.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- **update coworker role domain logic**
- **can update invitation role**
- **postgres adapter**
- **rest api**
- **integration test**
=> [B-1450] Implement the role endpoint

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/feature/RewardStatusIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000123_fix_reward_status_views.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **Add test to check that reward status doesn't change when we change payout preferences as long as it is in an invoice**
- **fix reward status computation**
=> [B-1484] Reward status changed from processing to pending

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/SponsorMapper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/SponsorsGetApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- **add total budget in usd**
- **add id and slug in ProjectLinkResponse**
=> [B-1504] Add missing data in get sponsor endpoint

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/PayoutInfoValidator.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/PayoutInfoValidatorTest.java, application/cli-adapter/pom.xml, application/cli-adapter/src/main/java/onlydust/com/marketplace/cli/EvmWalletSanitizer.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/AccountingConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/CliConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/InfuraConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/BillingProfileApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/feature/AlertingIT.java, infrastructure/infura-adapter/src/main/java/onlydust/com/marketplace/api/infura/adapters/InfuraEvmAccountAddressValidatorAdapter.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- **validate ethereum account addresses**
- **validate optimism account addresses**
- **fix IT**
=> Validate EVM account addresses

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/exception/OnlydustExceptionRestHandler.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/SwaggerConfiguration.java
it ain't much but it's honest work
=> Better swagger. Better error.

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/exception/OnlydustExceptionRestHandler.java, bff-read/pom.xml, bff-read/src/main/java/onlydust/com/marketplace/bff/read/BffReadConfiguration.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/adapters/BffReadUsersApiPostgresAdapter.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/LanguageViewEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/ProjectLinkViewEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/UserProfileLanguagePageItemEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/repositories/BffLanguageRepository.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/repositories/UserProfileLanguagePageItemEntityRepository.java, bootstrap/pom.xml, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/MarketplaceApiApplication.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/WebSecurityConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/UsersReadApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeLanguageApiIT.java, bootstrap/src/test/resources/database/scripts/change_data_for_testing.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000224_filter_users_languages_ranks_on_public_projects.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, pom.xml
- **new bff-read package**
- **move read endpoint to dedicated interface**
- **handle missing required param exception**
- **make page params optional**
- **add some languages for IT**
- **create first IT**
- **basic entry point implementation**
- **allow endpoint to anonymous users**
- **real repository and query**
- **add projects to response**
- **compute status correctly**
=> [B-1560] Implement /api/v2/users/{githubId}/languages

application/cron-adapter/src/main/java/com/onlydust/marketplace/api/cron/JobScheduler.java, bootstrap/src/main/resources/application.yaml, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresUserAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/UserRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000223_create_global_user_ranking_views.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/UserFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/UserStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/UserService.java
- **create users ranking views**
- **refresh user ranks every 5 minutes**
=> [B-1564] Implement user ranking

bff-read/pom.xml, bff-read/src/main/java/onlydust/com/marketplace/bff/read/BffReadConfiguration.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/adapters/BffReadUsersApiPostgresAdapter.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/BffUserViewEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/ContactInformationViewEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/GithubAccountViewEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/PublicUserProfileResponseV2Entity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/RegisteredUserViewEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/UserProfileEcosystemPageItemEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/UserProfileLanguagePageItemEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/entities/UserProfileViewEntity.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/repositories/PublicUserProfileResponseV2EntityRepository.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/repositories/UserProfileEcosystemPageItemEntityRepository.java, bff-read/src/main/java/onlydust/com/marketplace/bff/read/repositories/UserProfileLanguagePageItemEntityRepository.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/UsersReadApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000226_add_global_user_rank_percentile.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- **first implementation**
- **add ecosystems**
- **add user stats**
- **add rank percentiles in views to simplify queries**
- **add github signup date**
=> [B-1558] Implement /api/v2/users/{githubId} and /api/v2/users/slug/{slug}

bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/MarketplaceApiApplication.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/UsersReadApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/bff/read/ReadApiConfiguration.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/adapters/ReadUsersApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/UserProfileProjectEarningsEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/UserWeeklyStatsEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/UserWorkDistributionEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/UserProfileProjectEarningsEntityRepository.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/UserWeeklyStatsEntityRepository.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/UserWorkDistributionEntityRepository.java
- **rename BffRead to Read**
- **get project earnings**
- **get work distribution**
- **get user activity**
- **filter by ecosystem**
=> [B-1559] Implement /api/v2/users/{githubId}/stats

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/UserProfileUpdateApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/UserProfileInfoEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/mapper/UserMapper.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000232_make_weekly_allocated_time_optional.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000233_make_looking_for_a_job_optional.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, infrastructure/postgres-adapter/src/test/java/onlydust/com/marketplace/api/postgres/adapter/it/repository/AllRepositoriesIT.java
- **make weekly allocated time optional (#685)**
- **handle minimal profile update**
=> Handle minimal profile creation

application/cli-adapter/src/main/java/onlydust/com/marketplace/cli/PennylaneMigrationRecovery.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/CliConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/PayoutPreferenceApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresSponsorAccountStorageAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/RewardEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/SponsorAccountEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000241_pennylane_migration_recovery.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **lazy loading of sponsor account transactions**
- **add currency relationship in reward entity**
- **migration recovery script**
=> Pennylane migration recovery batch

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeCommitteeManagementRestApi.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeCommitteeAccountingApiIT.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/CommitteeFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/CommitteeService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/CommitteeServiceTest.java
- **improve committee allocation algo**
- **remove min/max in budget allocation**
=> Rework committee budget allocation algo

marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
closes B-1765
closes B-1766
closes B-1767
closes B-1768
=> define contracts for ecosystem overview

project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/JuryAssignment.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/CommitteeService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/CommitteeServiceTest.java
- **fix allocation algo**
- **cannot close committee if a project score is missing**
- **fix score computation**
- **remove impossible test**
=> Budget allocation fixes

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Currency.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/CurrencyFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/CurrencyService.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeCommitteeManagementRestApi.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/BackofficeConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/BackOfficeCommitteeAccountingApiIT.java, kernel/src/main/java/onlydust/com/marketplace/kernel/Utils/CurrencyConversion.java, kernel/src/main/java/onlydust/com/marketplace/kernel/mapper/AmountMapper.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/CommitteeFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/CommitteeService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/CommitteeServiceTest.java
- **add precision to budget allocation algo**
- **extract scale computation logic**
- **update IT**
=> Smart rounding of committee budget allocations

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/billingprofile/BillingProfile.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/billingprofile/CompanyBillingProfile.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/billingprofile/IndividualBillingProfile.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/billingprofile/SelfEmployedBillingProfile.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileService.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/view/ShortBillingProfileView.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/service/BillingProfileServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BillingProfileMapper.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresBillingProfileAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/BillingProfileStatsViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ShortBillingProfileQueryEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/BillingProfileEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ShortBillingProfileViewRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000254_create_mandate_acceptance_outdated.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/bff/read/ReadMarketplaceApiConfiguration.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/adapters/ReadMeApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/GlobalSettingsReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/billing_profile/AllBillingProfileUserReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/billing_profile/BillingProfileReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/billing_profile/BillingProfileStatsReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/billing_profile/BillingProfileUserInvitationReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/user/AllUserReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/AllBillingProfileUserReadRepository.java
- **migrate get my billing profiles to read api**
- **add mandate acceptance computation in view**
- **deduplicate results**
=> Migrate get my billing profiles to read api

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/EcosystemReadApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/EcosystemsApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/CustomProjectRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000260_create_public_projects.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/ecosystem/EcosystemReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/project/PublicProjectReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/mapper/ProjectMapper.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/ProjectEcosystemCardReadEntityRepository.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/ProjectsPageFiltersRepository.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/ProjectsPageRepository.java
- **create public_projects view**
- **return only public projects in read ecosystem**
=> public projects in ecosystem read

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeReadApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000262_create_project_similarities_view.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/bff/read/ReadMarketplaceApiConfiguration.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/adapters/ReadMeApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/project/PublicProjectReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/PublicProjectReadRepository.java
- **extract common page properties**
- **create /me/recommended-projects endpoint**
=> [B-1869] Add /me/recommended-projects endpoint

bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeReadApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/bff/read/ReadMarketplaceApiConfiguration.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/adapters/ReadMeApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/user/AllUserReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/user/JourneyCompletionEntity.java
=> [B-1868] Create /me/journey endpoint

.run/CI.run.xml, .run/Integration tests.run.xml, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/resources/database/scripts/refresh_materialized_views.sql, bootstrap/src/test/resources/database/scripts/restore_db.sh, docker-compose-IT-db.yaml
- **refresh materialized views only once during first restore**
- **sequential IT is now faster than parallel IT**
=> Improve CI perfs

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/AccountingFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/AccountingRewardPort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/BillingProfileFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/CurrencyFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/InvoiceFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/PaymentPort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/PayoutPreferenceFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/SponsorFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeAccountingManagementRestApi.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/bff/read/ReadBackofficeApiConfiguration.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/adapters/BackofficeAccountingReadApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/accounting/SponsorAccountAllowanceTransactionReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/accounting/SponsorAccountReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/accounting/SponsorAccountTransactionReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/currency/CurrencyReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/reward/ReceiptReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/reward/RewardDetailsReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/reward/RewardStatusDataReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/reward/RewardStatusReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/entities/sponsor/SponsorReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/bff/read/repositories/SponsorAccountReadRepository.java
- **migrate some views to read api**
- **add todos in accounting domain**
- **migrate get sponsor accounts to read-api**
=> Migrate get sponsor accounts to read api

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/ApplicationsRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/ProjectConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/bootstrap/configuration/RestApiConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/bootstrap/it/api/MeProjectApplicationIT.java, infrastructure/slack-adapter/src/main/java/onlydust/com/marketplace/api/slack/SlackApiAdapter.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/observer/ApplicationObserverComposite.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/observer/ProjectObserverComposite.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/ApplicationFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/ProjectObserverPort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/UserFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/ApplicationService.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/ContributionService.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/OutboxService.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/UserService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/ApplicationServiceTest.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/UserServiceTest.java
- **split application service from user service**
- **move onUserApplied to application observer**
=> Some refactoring

bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/ProjectConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ApplicationsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/GithubEventProcessingIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeProjectApplicationIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresUserAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/read/ApplicationRankingViewEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/ApplicationEntity.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000273_add_recommendation_score_in_view.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, infrastructure/posthog-api-client-adapter/src/main/java/onlydust/com/marketplace/api/posthog/adapters/PosthogApiClientAdapter.java, infrastructure/posthog-api-client-adapter/src/main/java/onlydust/com/marketplace/api/posthog/processors/ApplicationCreatedEventReader.java, infrastructure/posthog-api-client-adapter/src/main/java/onlydust/com/marketplace/api/posthog/processors/GithubIssueAssignedEventReader.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/job/TrackingEventPublisherOutboxConsumer.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/Application.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/ScoredApplication.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/event/OnApplicationCreated.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/event/OnApplicationCreatedTrackingEvent.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/event/OnGithubIssueAssignedTrackingEvent.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/UserStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/OutboxService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/job/TrackingEventPublisherOutboxConsumerTest.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ApplicationRankingReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ApplicationReadEntity.java
- **move recommendation score logic in view**
- **add all scores in posthog events**
- **publish on application created to posthog**
=> [B-2008] Send events onApplicationCreated to posthog

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectGoodFirstIssuesApiIT.java, bootstrap/src/test/resources/database/scripts/refresh_materialized_views.sql, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/LanguageRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubIssueReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubRepoReadEntity.java
- **refresh repo languages**
- **add GFI languages**
=> Fix languages in good first issues

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeProjectApplicationIT.java, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/GithubHttpClient.java, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/adapters/GithubApiAdapter.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/GithubApiPort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/ApplicationService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/ApplicationServiceTest.java
- **add application details in github comment**
- **fix NPE when user is not registered (#860)**
- **update github comment when updating application**
=> [B-2031] Update GitHub comment when updating an application from marketplace

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeBannersRestApi.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/ProjectConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/WebSecurityConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/BannerApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackOfficeBannerApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresBannersAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/BannerEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/BannerRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000276_create_banners.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/Banner.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/BannerFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/BannerStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/BannerService.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/BackofficeBannersReadApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadBannerApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/BannerReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/BannerReadRepository.java
- **create contract**
- **create models**
- **get banner page endpoint**
- **create banner endpoint**
- **get banner by id endpoint**
- **update banner endpoint**
- **delete banner endpoint**
- **hide show banner**
- **test get banner page**
- **create get banner marketplace endpoint**
=> [B-2036][B-2037] Banner management

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ApplicationsApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubAccountReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubIssueReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ApplicationReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ApplicationReadRepository.java
- **fix typo**
- **add info in get applications**
=> add info in applications

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectsGetIssuesApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadMeApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProjectsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubIssueReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/reward/RewardReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/reward/RewardStatusReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/user/AllUserReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/GithubIssueReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/RewardReadRepository.java
closes B-2064
closes B-2066
closes B-2067
=> Project issues improvements

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Country.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Currency.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/CurrencyFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/CurrencyService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/CurrencyServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeCurrencyManagementRestApi.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/mapper/BackOfficeMapper.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackOfficeAccountingApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackOfficeCurrencyApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresCurrencyAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/CurrencyEntity.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000282_add_currency_country_restrictions.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, infrastructure/postgres-adapter/src/test/java/onlydust/com/marketplace/api/postgres/adapter/it/adapters/PostgresQuoteAdapterIT.java
- **improve currency country restriction**
- **manage country restrictions in REST API**
=> Improve currency country restrictions

bootstrap/src/test/java/onlydust/com/marketplace/api/suites/OthersSuite.java
=> "Others" IT suite was running ITs tagged with Concurrency

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/IssuesApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectGetPublicIssuesApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubIssueReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubRepoReadEntity.java
- Replace every GithubRepoLinkResponse with ShortGithubRepoResponse
- Add assignees to GithubIssueResponse
=> b 2182 replace every githubrepolinkresponse with

bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/ProjectConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeProjectApplicationIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresHackathonAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/HackathonRepository.java, infrastructure/slack-adapter/src/main/java/onlydust/com/marketplace/api/slack/SlackApiAdapter.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/job/ApplicationMailNotifier.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/job/ApplicationsUpdater.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/observer/ApplicationObserverComposite.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/observer/GithubIssueCommenter.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/ApplicationObserverPort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/HackathonStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/OutboxService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/job/ApplicationsUpdaterTest.java
- Add (failing) IT to check that an external application to an ODHack issue is ignored
- Add (failing) UT to check that an external application to an ODHack issue is ignored
- Auto-refuse external applications (from github) to ODHack issues
=> b 2157 auto refuse external applications from github to odhack

bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackOfficeBatchPaymentApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardStatusRepository.java
- Add (failing) IT reproducing the bug
- Fix bug
=> e 1598 bug some invoices have status approved instead of paid

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/MeRestApi.java, bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/UserDomainConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeNotificationSettingsIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresNotificationSettingsAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/NotificationSettingsForProjectEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/NotificationSettingsForProjectRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000294_create_notification_settings_for_project_table.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadMeApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/user/NotificationSettingsForProjectReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/NotificationSettingsForProjectReadRepository.java, user-domain/src/main/java/onlydust/com/marketplace/user/domain/model/NotificationSettings.java, user-domain/src/main/java/onlydust/com/marketplace/user/domain/model/ProjectId.java, user-domain/src/main/java/onlydust/com/marketplace/user/domain/model/UserId.java, user-domain/src/main/java/onlydust/com/marketplace/user/domain/port/input/NotificationSettingsPort.java, user-domain/src/main/java/onlydust/com/marketplace/user/domain/port/output/NotificationSettingsStoragePort.java, user-domain/src/main/java/onlydust/com/marketplace/user/domain/service/NotificationSettingsService.java
- **Implement PATCH /api/v1/me/notification-settings/projects/{projectId}**
- **Implement GET /api/v1/me/notification-settings/projects/{projectId}**
=> b 2230 api add endpoint to save user notification preferences

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeNotificationSettingsIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/NotificationSettingsForProjectEntity.java
I could not reproduce the bug, so I don't know if this fixes anything.
See https://app.datadoghq.eu/apm/trace/66a7068100000000064f33c8104e7270?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=891874136182092666&spanViewType=metadata&timeHint=1722222209778.488&view=spans
=> Trying to fix "duplicate key value violates unique constraint "user_projects_notification_settings_pkey"

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProgramsApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProgramsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/accounting/AccountBookTransactionReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/accounting/SponsorAccountReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/sponsor/SponsorReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/AccountBookTransactionReadRepository.java
- **implement get program transactions**
- **add filter by search**
- **filter by type**
=> [B-2337] Implement get Program transactions

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProgramsApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000311_create_project_stats_view.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProgramsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/program/ProgramReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/program/ProgramTransactionStat.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectStatPerCurrencyReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectStatReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/mapper/DetailedTotalMoneyMapper.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectStatsReadRepository.java
- **create contract**
- **implement get program projects endpoint**
=> [B-2365] Implement get program projects

application/cron-adapter/src/main/java/com/onlydust/marketplace/api/cron/JobScheduler.java, bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/CronIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeReadApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectsPageApiIT.java, bootstrap/src/test/resources/database/scripts/refresh_materialized_views.sql, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ProjectRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000315_create_project_recommendations.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/ProjectFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/ProjectStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/ProjectService.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadMeApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProjectsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/mapper/ProjectMapper.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectsPageRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/PublicProjectReadRepository.java
- **create project recommendation views**
- **add order by recommendation score**
- **update get recommended projects**
=> [B-2381] Compute project recommendation ranks

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProgramsApiIT.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/program/ProgramReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/program/ProgramStatPerCurrencyPerProjectReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/program/ProgramStatPerCurrencyReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectContributionStatReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectRewardStatReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectStatPerCurrencyReadEntity.java
- **improve some query perfs**
- **move IT to correct suite**
=> Improve get project by slug performances

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeReadApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000316_update_project_recommendations.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectsPageRepository.java
- **include user languages in recommendation**
- **default sort by recommended projects for authenticated users**
- **fix tests**
=> Fix recommendation algo

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBookAggregate.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBookObserver.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBookProjector.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/accountbook/AccountBookTransactionProjection.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceTest.java, application/cli-adapter/src/main/java/onlydust/com/marketplace/cli/AccountBookRefresh.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProgramsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/SponsorsApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresAccountBookStorageAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/AccountBookTransactionEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/AccountBookTransactionRepository.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProgramsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadSponsorsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/accounting/AccountBookTransactionReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/AccountBookTransactionReadRepository.java
- **implement GET sponsor transactions**
- **group transfers and refunds**
- **group transactions during projection**
- **revert grouping in observer**
- **add export transactions in csv**
- **remove flakiness**
=> [B-2406][B-2407] Add GET sponsor transactions

bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/AccountingConfiguration.java, bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/WebSecurityConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/SupportedCurrenciesApiIT.java, bootstrap/src/test/resources/application-it.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadCurrencyApiPostgresAdapter.java
For now, there is no value in the application.yml so currencies' supportedNetworks will all be empty arrays (until we add them to application.yml)
=> Implement GET /currencies endpoint

README.md
- **Add instructions to sign commits**
- **Add instructions for JetBrains**
=> Add instructions to setup commits signing

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/Currency.java, bootstrap/src/test/java/onlydust/com/marketplace/api/helper/CurrencyHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/DepositsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackOfficeCurrencyApiIT.java, bootstrap/src/test/resources/wiremock/aptos/__files/body-apt-info.json, bootstrap/src/test/resources/wiremock/aptos/__files/body-transaction-transfer-aptos.json, bootstrap/src/test/resources/wiremock/aptos/__files/body-transaction-transfer-usdc.json, bootstrap/src/test/resources/wiremock/aptos/__files/body-usdc-info.json, bootstrap/src/test/resources/wiremock/aptos/mappings/apt-info.json, bootstrap/src/test/resources/wiremock/aptos/mappings/transaction-transfer-aptos.json, bootstrap/src/test/resources/wiremock/aptos/mappings/transaction-transfer-usdc.json, infrastructure/aptos-rpc-adapter/src/main/java/onlydust/com/marketplace/api/infrastructure/aptosrpc/RpcClient.java, infrastructure/aptos-rpc-adapter/src/main/java/onlydust/com/marketplace/api/infrastructure/aptosrpc/adapters/AptosTransactionStorageAdapter.java, pom.xml
- **aptos transaction storage adapter**
- **handle decimals**
- **add test case for usdc on aptos**
- **bump kernel version**
=> [B-2419] Implement Aptos transaction storage adapter

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/JSONPathAssertion.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProgramsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/SponsorsApiIT.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/AccountBookTransactionReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProgramTransactionMonthlyStatsReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/SponsorTransactionMonthlyStatsReadRepository.java
- **remove dead code**
- **fix transaction stats**
- **fix expectation message**
=> [B-2439] Fix transaction count in side panel

backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/helper/DepositHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackOfficeSponsorApiIT.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/BackofficeSponsorsReadApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/accounting/DepositReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/accounting/TransferTransactionReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/sponsor/SponsorReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/DepositReadRepository.java
=> [B-2424] Implement get sponsor deposits

accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/model/SponsorAccount.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/port/in/AccountingFacadePort.java, accounting-domain/src/main/java/onlydust/com/marketplace/accounting/domain/service/AccountingService.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceConcurrencyTest.java, accounting-domain/src/test/java/onlydust/com/marketplace/accounting/domain/AccountingServiceTest.java, application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeSponsorManagementRestApi.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/AccountingConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackOfficeSponsorApiIT.java
- **implement reject deposit from back-office**
- **implement approve deposit**
- **handle deposit on account with debt**
=> [B-2425] Approve/reject deposit from Back Office

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectGetStatsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/WorldMapKpiApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/AbstractMarketplaceBackOfficeApiIT.java, bootstrap/src/test/resources/database/scripts/refresh_materialized_views.sql, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ProjectRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000333_update_bi_project_contributors_view.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProjectsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectCustomStatReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectCustomStatsReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/WorldMapKpiReadRepository.java
- **remove unused fields**
- **update bi views**
- **return onboarded dev count**
=> [B-2482] Add onboarded contributor count in project stats

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/CountriesApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/EcosystemsApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadCountriesApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadEcosystemsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/CountryReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/CountryReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/EcosystemReadRepository.java
- **add get countries**
- **add search by name for ecosystems**
=> add missing endpoints

bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/UserProfileUpdateApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/UserProfileInfoEntity.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000348_add_missing_indexes.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000349_make_contact_email_nullable.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **add missing indexes**
- **increase db pool size**
=> Improve perfs a bit

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/RewardHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectTransactionsApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProjectsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/accounting/AllTransactionReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/user/AllUserReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/AllTransactionReadRepository.java
- **Update contract**
- **Implement GET project transactions endpoint**
- **Implement extract project transactions CSV endpoint**
=> e 1927 implement get projectsprojectidstatstransactions

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/ProjectsRestApi.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectContributorLabelApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectsGetContributorsApiIT.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectContributorLabelAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/ContributorProjectContributorLabelEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/ContributorProjectContributorLabelRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000353_create_contributors_project_contributor_labels_table.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/input/ProjectContributorLabelFacadePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/ProjectContributorLabelStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/ProjectContributorLabelService.java
- **Implement PATCH endpoint to assign labels to contributors**
=> e 1933 create patch projectsprojectidcontributors endpoint

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorDeepKpisApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorDiagramKpisApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ProjectDeepKpisApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ProjectDiagramKpisApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/WorldMapKpiApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000357_refactor_datasource_param.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadBiApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/AggregatedKpisReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributorKpisReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectKpisReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/WorldMapKpiReadRepository.java
- **Iso migration**
- **Replace programOrEcosystemIds filter with dataSourceIds filter**
=> e 2044 project leads cannot access get bicontributors

infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/BackofficeEarningsViewRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/BackofficeRewardViewRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/BillingProfileUserRightsViewRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/RewardStatusRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000362_optimize_reward_statuses_usage.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectContributorQueryRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/RewardDetailsReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/UserRewardStatsReadRepository.java
- **Revamp VIEW accounting.reward_statuses**
- **Refactor accounting.reward_statuses usages**
- **Improve accounting.reward_statuses again, and accounting.billing_profile_stats**
=> e 2140 optimise GET billing profiles

infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000366_fix_deadlocks.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **Iso refresh procedures**
- **Fix deadlocks by ordering inserts**
- **Avoid performing unnecessary inserts (event if the final result is the same)**
- **Slightly improve perf of partial refresh**
- **Iso v_contribution_data**
- **Put back forgotten optimizations of v_contribution_data**
- **Bitch**
=> Fix deadlocks & improve refresh

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ContributionsApiIT.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributionReadRepository.java
- **add projectIds filter**
- **add porjectSlugs filters**
- **refactor test**
- **add statuses filter**
- **add repoIds filter**
- **remove unnecessary casts**
- **add contributorIds filter**
- **add hasBeenRewarded filter**
=> add contributions filters

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ApplicationsApiIT.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadIssuesApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributorKpisReadRepository.java
- **add test**
- **include contributor labels in get applicants**
=> [E-2244] Include contributor labels in get applicants

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ReadBiFinancialStatsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorDeepKpisApiIT.java, bootstrap/src/test/resources/database/dumps/IT_data.dump, bootstrap/src/test/resources/database/dumps/IT_schema.dump, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresBiProjectorAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/bi/BiContributorApplicationDataRepository.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/bi/BiContributorRewardDataRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000370_split_contributor_global_data.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml
- **Split contributor_global_data projection**
- **Fix flakiness on financial IT**
- **Update dumps**
=> fix perf contributor global data

bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/ProjectConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeProjectApplicationIT.java, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/GithubHttpClient.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/job/ApplicationsUpdater.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/Application.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/job/ApplicationsUpdaterTest.java
- **create application on assigned issues**
- **update comment body upon comment edited on github**
=> Handle github comment update

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/GithubHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorActivityGraphApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadBiApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/bi/ContributorActivityGraphDayReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributorActivityGraphReadRepository.java
- **Implement endpoint /api/v1/bi/contributors/{contributorId}/activity-graph**
- **Add IT**
=> e 2001 create get apiv1contributorsgithubidactivity graph

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/GithubHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorDeepKpisApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000377_add_index.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadBiApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/bi/ContributorKpisReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/bi/ContributorReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributorKpisReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributorReadRepository.java
- **Refactor contributors query**
- **Refactor contributorById query**
- **Add repos to contributor response**
- **Add top repo languages to contributor response**
- **Add missing indexes**
=> Add repos to GET /contributors/{id}

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/AccountingHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/GetRewardsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectsPageApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/bo/BackofficeBiApiIT.java, bootstrap/src/test/resources/database/dumps/IT_data.dump, bootstrap/src/test/resources/database/dumps/IT_schema.dump, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000384_contribution_uuids_in_reward_data.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadRewardsPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/reward/RewardV2ReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/RewardReadV2Repository.java
- **Update contract**
- **Iso reward_data**
- **Add contribution_uuids to reward_data**
- **Implement new fields in response**
- **Fix migration**
- **Add ITs + fix**
=> b 2705 modifier v1rewards

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ContributionsApiIT.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000385_add_index.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributionReadRepository.java
- **Add applicantIds query param to /contributions**
- **Add missing index**
- **Add IT**
=> b 2765 add applicantuserid queryparams to get the issue where user

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ContributionsApiIT.java, bootstrap/src/test/resources/database/dumps/IT_indexer.dump, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000024_add_assigned_by_into_contribution_contributors_data.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, infrastructure/postgres-adapter/src/test/resources/db_init_script/init_indexer_exp_schema.sql, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/bi/ContributionReadEntity.java
- **Iso v_contribution_contributors_data**
- **Add assignedBy to v_contribution_contributors_data**
- **Add assignedBy to contributors of ContributionActivityPageItemResponse**
- **Update indexer dump**
- **Return assignedBy in contributions**
=> Add assignedBy in contributions' contributors

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/GithubHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ContributionsApiIT.java, bootstrap/src/test/resources/database/dumps/IT_data.dump, bootstrap/src/test/resources/database/dumps/IT_indexer.dump, bootstrap/src/test/resources/database/dumps/IT_schema.dump, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000025_add_merged_by_into_contribution_contributors_data.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, infrastructure/postgres-adapter/src/test/resources/db_init_script/init_indexer_exp_schema.sql, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/bi/ContributionReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributionReadRepository.java
- **Add github_merged_by to contribution_contributors_data**
- **Return mergedBy in ContributionActivityPageItemResponse**
=> b 2703 ajouter mergedby dans get apiv1contributionscontributionuuid

read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadBannerApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadContributionsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProjectsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/properties/Cache.java, read-api/src/test/java/onlydust/com/marketplace/api/read/CacheTest.java
- **Allows to set a different cache durations for authenticated and anonymous users**
- **Do not send 'public' in Cache-Control when using 'whenAnonymous' method**
=> improve cache

application/cron-adapter/src/main/java/com/onlydust/marketplace/api/cron/JobScheduler.java, bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/ProjectConfiguration.java, bootstrap/src/main/resources/application.yaml, bootstrap/src/test/java/onlydust/com/marketplace/api/helper/ApplicationHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeProjectApplicationIT.java, bootstrap/src/test/resources/application-it.yaml, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/adapters/GithubApiAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/PostgresProjectApplicationAdapter.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/configuration/PostgresConfiguration.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/GithubCommandEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/entity/write/old/ApplicationEntity.java, infrastructure/postgres-adapter/src/main/java/onlydust/com/marketplace/api/postgres/adapter/repository/GithubCommandRepository.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000031_github_commands_outbox.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, project-domain/src/main/java/onlydust/com/marketplace/project/domain/job/GithubCommandOutboxConsumer.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/job/githubcommands/GithubCommandOutboxConsumer.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/job/githubcommands/GithubCreateCommentCommandConsumer.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/Application.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/model/event/GithubCreateCommentCommand.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/GithubApiPort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/port/output/ProjectApplicationStoragePort.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/ApplicationService.java, project-domain/src/main/java/onlydust/com/marketplace/project/domain/service/GithubCommandService.java, project-domain/src/test/java/onlydust/com/marketplace/project/domain/service/ApplicationServiceTest.java
- **Reproduce concurrency issue**
- **Refactor to use OutboxPattern instead of creating github comment synchronously within DB tx**
- **Fix retryable**
- **Implement duplicate key error handling logic**
- **Update UT**
=> e 2501 erreur de cle dupliquee dans la table applications en prod

application/rest-api-adapter/src/main/java/onlydust/com/marketplace/api/rest/api/adapter/BackofficeMeRestApi.java, backoffice-api-contract/src/main/resources/backoffice-api-contract.yaml, bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/WebSecurityConfiguration.java, bootstrap/src/main/resources/application.yaml, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000033_add_bo_user_role_tech_admin.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, user-domain/src/main/java/onlydust/com/marketplace/user/domain/model/BackofficeUser.java
Cf. https://www.baeldung.com/spring-boot-changing-log-level-at-runtime
Examples:
```sh
curl http://localhost:8080/actuator/loggers/com.baeldung.spring.boot.management.logging
{"configuredLevel":null,"effectiveLevel":"INFO"}
```
```sh
curl -i -X POST -H 'Content-Type: application/json' -d '{"configuredLevel": "TRACE"}'
http://localhost:8080/actuator/loggers/com.baeldung.spring.boot.management.logging
HTTP/1.1 204
Date: Mon, 02 Sep 2019 13:56:52 GMT
```
=> Expose actuator loggers endpoint to be able to see and change the log level of any logger at runtime

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/GithubHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorDeepKpisApiIT.java, bootstrap/src/test/resources/database/dumps/IT_indexer.dump, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000041_add_follower_count_to_bi_view.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, infrastructure/postgres-adapter/src/test/resources/db_init_script/init_indexer_exp_schema.sql, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml
- **iso contributor_global_data**
- **update indexer dump**
- **add follower count**
=> Add follower count in get BI contributors

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/GithubHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ContributionsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorActivityGraphApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorDeepKpisApiIT.java, infrastructure/github-api-adapter/src/main/java/onlydust/com/marketplace/api/github_api/GithubHttpClient.java, infrastructure/postgres-adapter/src/main/resources/db/changelog/changelogs/00000043_remove_private_repos.sql, infrastructure/postgres-adapter/src/main/resources/db/changelog/db.changelog-master.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ContributorReadRepository.java
- **remove private repos from contributor response**
- **iso contribution_data**
- **remove private repos from contributions**
- **add test for activity graph**
=> remove private repos from contribution stats

bootstrap/src/test/java/onlydust/com/marketplace/api/helper/DatabaseHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/helper/GithubHelper.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ContributionsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/MeReadProjectsApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectGetPublicIssuesApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ProjectsPageApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ReadProjectsV2ApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/bi/ContributorDeepKpisApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/feature/GoodFirstIssueCreatedNotifierJobIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/me/MeProjectsAsContributorApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProjectsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/GithubLabelWithCountReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/github/ProjectGithubIssueItemReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/GithubLabelWithCountReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectGithubIssueItemReadRepository.java
- **refactor github helper**
- **implement get project available issues**
- **add comment count**
=> [B-2858] Implement get project available issues

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/ReadProjectsV2ApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadProjectsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/bi/ContributorKpisReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectContributorV2ReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectRewardV2ReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectV2ReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/user/PublicUserProfileResponseV2Entity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectContributorV2ReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectRewardV2ReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectsV2ReadRepository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/utils/RankingUtils.java
closes B-2863
closes B-2885
closes B-2883
=> Update projects v2 endpoints

bootstrap/src/main/java/onlydust/com/marketplace/api/configuration/WebSecurityConfiguration.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/HackathonApiIT.java, marketplace-api-contract/src/main/resources/marketplace-api-contract.yaml, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadHackathonsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/hackathon/HackathonV2ReadEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/HackathonV2ReadRepository.java
- **fix contract**
- **implement get hackathon by slug v2**
=> Implement get hackathon by slug v2

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/HackathonApiIT.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadHackathonsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/BaseProjectPageV2ItemQueryEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectPageV2ItemQueryEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/entities/project/ProjectPageV2ItemWithOdHackQueryEntity.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectsPageV2Repository.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/ProjectsPageV2WithOdHackStatsRepository.java
- **implement get hackathon projects**
- **add od hack stats**
- **add test**
=> Implement get hackathon projects

bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/AbstractMarketplaceApiIT.java, bootstrap/src/test/java/onlydust/com/marketplace/api/it/api/HackathonApiIT.java, read-api/src/main/java/onlydust/com/marketplace/api/read/adapters/ReadHackathonsApiPostgresAdapter.java, read-api/src/main/java/onlydust/com/marketplace/api/read/repositories/HackathonEventReadRepository.java
=> Implement get hackathon events
